baseURL = "https://therookiecoder.is-a.dev/"
languageCode = "en-us"
title = "theRookieCoder"
theme = ["hugo-video"]


[module]
[[module.imports]]
path = "github.com/panr/hugo-theme-terminal/v4"


[markup]
[markup.tableOfContents]
startLevel = 1


[params.logo]
logoText = "theRookieCoder"
logoHomeLink = "/"


[params]

# GENERAL WEBSITE SETTINGS

subtitle = "theRookieCoder's website and blog"
owner = "Ilesh Thiada (theRookieCoder)"
keywords = ""
copyright = ""
menuMore = "Socials"
readMore = "Read more"
readOtherPosts = "Read other posts"
newerPosts = "Newer posts"
olderPosts = "Older posts"
missingContentMessage = "Page not found..."
missingBackButtonLabel = "Back to home page"
minuteReadingTime = "min read"
words = "words"

# THEME SETTINGS

# contents directory
contentTypeName = "posts"

showMenuItems = 4

# don't allow switching languages
showLanguageSelector = false

# don't set theme to full screen width
fullWidthTheme = false

# center theme with default width
centerTheme = true

# if your resource directory contains an image called `cover.(jpg|png|webp)`,
# then the file will be used as a cover automatically.
# With this option you don't have to put the `cover` param in a front-matter.
autoCover = true

# set post to show the last updated
# If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
showLastUpdated = false

# Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
# updatedDatePrefix = "Updated"

# whether to show a page's estimated reading time
readingTime = true

# whether to show a table of contents
Toc = true

# set title for the table of contents
# can be overridden in a page's front-matter
# TocTitle = "Table of Contents" # default

# Set date/time format for posts
# This will impact the date/time displayed on
# index.html, the posts list page, and on posts themselves
# Default value: (ISO 8601)
# dateFormat = "2006-01-02"


[menu]

[[menu.main]]
identifier = "home"
name = "Home"
pageref = "/"
weight = -4

[[menu.main]]
identifier = "me"
name = "About Me"
pageref = "/me/"
weight = -3

[[menu.main]]
identifier = "setup"
name = "My Setup"
pageref = "/setup/"
weight = -2

[[menu.main]]
identifier = "showcase"
name = "Showcase"
pageref = "/showcase/"
weight = -1

[[menu.main]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/therookiecoder"

[[menu.main]]
identifier = "github"
name = "GitHub"
url = "https://github.com/theRookieCoder"

[[menu.main]]
identifier = "mastodon"
name = "Mastodon"
url = "https://fosstodon.org/@theRookieCoder"
